# Generated by Django 5.2.4 on 2025-08-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_message_session_delete_chatsession_and_more'),
    ]

    operations = [
    ]
