# Generated by Django 5.2.4 on 2025-08-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_auto_20250804_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('source_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'football_news',
                'ordering': ['-published_at'],
                'managed': False,
            },
        ),
    ]
