# Generated by Django 5.2.6 on 2025-10-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(help_text='Descriptive name for the search', max_length=100),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='search_params',
            field=models.JSONField(help_text='Applied search parameters'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='selected_metrics',
            field=models.JSONField(help_text='Selected metrics for the dashboard'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='selected_players',
            field=models.JSONField(help_text='Selected player IDs'),
        ),
    ]
