# Generated by Django 5.2.6 on 2025-10-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_savedsearch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=64, null=True)),
                ('position', models.CharField(blank=True, max_length=32, null=True)),
                ('club', models.CharField(blank=True, max_length=128, null=True)),
                ('team_logo', models.TextField(blank=True, null=True)),
                ('league', models.CharField(blank=True, max_length=64, null=True)),
                ('season', models.CharField(blank=True, max_length=10, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField()),
                ('league_base_rating', models.FloatField(blank=True, null=True)),
                ('performance_rating', models.FloatField(blank=True, null=True)),
                ('att', models.IntegerField(blank=True, help_text='Attacking', null=True)),
                ('ply', models.IntegerField(blank=True, help_text='Playmaking', null=True)),
                ('def_rating', models.IntegerField(blank=True, help_text='Defending', null=True)),
                ('ctr', models.IntegerField(blank=True, help_text='Ball Control', null=True)),
                ('phy', models.IntegerField(blank=True, help_text='Physical', null=True)),
                ('gkp', models.IntegerField(blank=True, help_text='Goalkeeping', null=True)),
                ('season', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=32, null=True)),
                ('minutes_played', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'player_ratings',
                'ordering': ['-overall_rating'],
                'managed': False,
            },
        ),
    ]
