# Generated by Django 5.2.3 on 2025-07-24 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.CreateModel(
            name='MessageVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'up'), (-1, 'down')])),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='upvoters',
            field=models.ManyToManyField(related_name='liked_messages', through='chats.MessageVote', through_fields=('message', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
