# Generated by Django 5.2.3 on 2025-07-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_options_messagevote_message_upvoters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='upvoters',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
        migrations.DeleteModel(
            name='MessageVote',
        ),
    ]
