# Generated by Django 5.2.4 on 2025-07-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_message_upvoters_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
